# Generated by Django 4.2.6 on 2024-02-29 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=64)),
                ('user_number', models.IntegerField()),
                ('user_age', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='rw',
            fields=[
                ('rw_id', models.AutoField(primary_key=True, serialize=False)),
                ('rw_name', models.CharField(max_length=20)),
                ('rw_fb_username', models.CharField(max_length=20)),
                ('rw_startdata', models.CharField(max_length=20)),
                ('rw_enddata', models.CharField(max_length=20)),
                ('rw_js_username', models.CharField(max_length=20)),
                ('rw_js_data', models.CharField(max_length=20)),
                ('rw_fb_userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo_fb_set', to='webapp01.userinfo')),
                ('rw_js_userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo_js_set', to='webapp01.userinfo')),
            ],
        ),
    ]
