# Generated by Django 4.2.6 on 2024-02-29 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rw',
            name='rw_js_state',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rw',
            name='rw_state',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rw',
            name='rw_js_data',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rw',
            name='rw_js_userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userinfo_js_set', to='webapp01.userinfo'),
        ),
        migrations.AlterField(
            model_name='rw',
            name='rw_js_username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
