# Generated by Django 4.2.6 on 2024-02-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp01', '0002_rw_rw_js_state_rw_rw_state_alter_rw_rw_js_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rw',
            name='rw_js_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rw',
            name='rw_state',
            field=models.BooleanField(default=False),
        ),
    ]
