# Generated by Django 4.2.6 on 2024-02-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp01', '0003_alter_rw_rw_js_state_alter_rw_rw_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='rw',
            name='rw_context',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
